version: '3.8'

services:
  redis:
    image: redis:alpine
    networks:
      - laravel

  mailhog:
    image: mailhog/mailhog
    ports:
      - "8025:8025"
    networks:
      - laravel

networks:
  laravel:
    external: true